### ISSUE TITLE
What if my SecretString is not JSON?

### ISSUE THREAD

**Issue by chillbrodev** [MoneyLion/bitrise-step-aws-secrets-manager#4]
Hello,

I am trying to use this step in my Bitrise workflow. It seems to be having an issue since my secret string is not JSON. Could this be patched to include a parseJson flag similar to how the [GitHub AWS Secrets Manager Action](https://github.com/marketplace/actions/aws-secrets-manager-action) works? 

I can take a crack at a PR later this week.

**Comment by raphlcx** [comment]
Hi @chillbrodev , thanks for raising the issue.

Yes, currently the step only supports JSON secret string, feel free to PR an implementation to support non-JSON secret string (greatly appreciated!).

The new non-JSON secret string feature will have to be an explicit flag, i.e. non-default behaviour to maintain backward compatibility with how the step work currently.

**Comment by raphlcx** [comment]
Hi @chillbrodev , thanks for raising the issue.

Yes, currently the step only supports JSON secret string, feel free to PR an implementation to support non-JSON secret string (greatly appreciated!).

The new non-JSON secret string feature will have to be an explicit flag, i.e. non-default behaviour to maintain backward compatibility with how the step work currently.

**Comment by chillbrodev** [comment]
I'll take a look at it this week and try to get a PR together. Thanks for the fast response. Stay tuned for a PR.

**Comment by chillbrodev** [comment]
@raphlcx PR is open for review

**Comment by raphlcx** [comment]
Thanks for the change, i'll release a new minor version with this feature soon.

**Comment by chillbrodev** [comment]
@raphlcx Could you reply here when this release is updated in Bitrise? I went to check the step and it still shows `2.1.X`. Thanks

**Comment by raphlcx** [comment]
It's still pending Bitrise to release them:
- https://github.com/bitrise-io/bitrise-steplib/pull/3730

i'll chime here when it's merged :)

**Comment by chillbrodev** [comment]
Looks like Bitrise merged it 7hrs ago. I tried the step on my Bitrise project and its working perfectly. Thanks for your assistance in getting this merged @raphlcx. 👍

**Comment by raphlcx** [comment]
awesome. thanks for bringing in the change!
